#!/usr/local/bin/python3

import click
import urllib3
import shutil


@click.command()
@click.option('--widget', nargs=1, help='The widget that you would like to generate.', type=str)
def generate(widget):
    """Flutterstrap generates Flutter customizable widgets out of the box."""

    base_url = 'https://github.com/p4p4l3gu4x/flutterstrap/blob/master/'
    if widget == 'login-form':
        click.echo('generating file for widget in root dir...')
        components_needed = ['textfield', ]
        get_latest_file_version()



def get_latest_file_version(url):
    filename = url.split("/")[-1]
    path = "widgets/"
    c = urllib3.PoolManager()

    with c.request('GET', url, preload_content=False) as resp, open(path+filename, 'wb') as out_file:
        shutil.copyfileobj(resp, out_file)

    resp.release_conn()  # not 100% sure this is required though


if __name__ == '__main__':
    generate()